---
name: Actions on PR by label
on:
  pull_request_target:
    types:
      - labeled

# by default, do not allow write access as pull_request_target has more write
# access than pull_request. assign necessary permissions as required in jobs.
permissions: read-all

jobs:
  on-labeled-ci-failure:
    # when a workflow fails, the PR is labeled with
    # `ci/${WORKFLOW_NAME}/failure`.
    if: ${{ startsWith(github.event.label.name, 'ci/') && endsWith(github.event.label.name, '/failure') }}
    runs-on: ubuntu-latest
    # this job needs write access to PRs because it modifies the PR by
    # creating a comment.
    permissions:
      pull-requests: write
    steps:
      - name: Dump context for debugging
        uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context, null, 2))

      - name: ci/Metadata/failure
        if: ${{ github.event.label.name == 'ci/Metadata/failure' }}
        uses: actions/github-script@v6
        with:
          script: |
            const util = require("util");
            try {
              await github.rest.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: util.format(
                  "@%s CI `Metadata` failed. Did you update README.md? Please run:\n" +
                  "\n" +
                  "```console\n" +
                  "bundle exec rake -C devtools readme > README.md\n" +
                  "```\n" +
                  "\n" +
                  "at the repository root directory and commit the changes.\n" +
                  "See also [Updating README](https://github.com/UncleRus/esp-idf-lib/blob/master/CONTRIBUTING.md#updating-readmemd)" +
                  "section in CONTRIBUTING.md. Thank you.",
                  context.payload.pull_request.user.login)
              });
            } catch(e) {
              core.error(e);
              core.setFailed(e.message);
            }
